### ISSUE TITLE
Add Entity Transformer Feature

### ISSUE THREAD

**Issue by stealth1980** [mbledsoe/Upswing#1]
In certain cases database naming conventions can vary.  A use case scenario is outlined below.

### Source Table : _Applications_T1_                       
-----------------------------------------                      
Application_IDNO                                           
FirstName_TEXT                                              
LastName_TEXT                                              
DOB_DTTM                                                     

### Current Entity Class Output: _Applications_T1.generated.cs_
------------------------------------------------------------------
Application_IDNO                                           
FirstName_TEXT                                              
LastName_TEXT                                              
DOB_DTTM

### Desired Transformation Example   Entity Class Output: _Applications.cs_
------------------------------------------------------------------------------------
ApplicationId
FirstName
LastName
DOB

**Comment by mbledsoe** [comment]
@stealth1980 I added some flexibility to the generation code.  Take a look at CreateEntityGenerator in Program.cs.  You'll see a DefaultEntityFileModelBuilder.  Go ahead and create your own custom EntityFileModelBuilder by creating a new class that implements the IEntityFileModelBuilder interface.  In that class you can do the name transformations that you want to do for the Entity and for the Properties.  Then, go back to Program.cs and change CreateEntityGenerator to instantiate your custom class instead of DefaultEntityFileModelBuilder.

**Comment by mbledsoe** [comment]
@stealth1980 check out that sweet SingletonPropertyNameTransformer.

**Comment by mbledsoe** [comment]
* Added INameTransformer interface
* Singleton added a class for his needs.

Closing issue.
